sudo: required

language: c

compiler:
  - gcc
python:
  - "3.7"

jobs:
  include:
  - name: "normal"
    dist: bionic
    addons:
      apt:
        sources:
        - sourceline: 'ppa:kvilhaugsvik/backports'
        packages:
        - gettext
        - libgtk-3-dev
        - libcurl4-openssl-dev
        - libtool
        - automake
        - autoconf
        - autotools-dev
        - language-pack-en
        - python3.7
        - liblzma-dev
        - libicu-dev
        - libsqlite3-dev
        - qt5-default
        - libsdl2-mixer-dev
        - libsdl2-gfx-dev
        - libsdl2-image-dev
        - libsdl2-ttf-dev
        - libmysqlclient-dev
  - name: "dist"
    dist: bionic
    addons:
      apt:
        packages:
        - libtolua-dev
        - gettext
        - libtool
        - automake
        - autoconf
        - autotools-dev
        - python3.7
        - liblzma-dev
        - libicu-dev
        - libsqlite3-dev
  - name: "meson"
    dist: bionic
    addons:
      apt:
        sources:
        - sourceline: 'ppa:kvilhaugsvik/backports'
        packages:
        - meson
        - libtolua-dev
        - gettext
        - libgtk-3-dev
        - libcurl4-openssl-dev
        - libtool
        - automake
        - autoconf
        - autotools-dev
        - language-pack-en
        - python3.7
        - liblzma-dev
        - libicu-dev
        - libsqlite3-dev
        - qt5-default
        - libsdl2-mixer-dev
        - libsdl2-gfx-dev
        - libsdl2-image-dev
        - libsdl2-ttf-dev
        - libmysqlclient-dev
  - name: "os_x"
    os: osx
    osx_image: xcode11.3
    addons:
      homebrew:
        packages:
          - autoconf
          - automake
          - gettext
          - libtool
          - pkg-config
          - atk
          - freetype
          - gettext
          - glib
          - gtk+3
          - icu4c
          - pango

script: "sudo bash ./scripts/travis-build.sh ${TRAVIS_JOB_NAME}"
